name 'docker_factory'
maintainer 'Allen Madsen'
maintainer_email 'blatyo@gmail.com'
license 'MIT'
description 'Installs/Configures an ubuntu machine to build docker images.'
long_description 'Installs/Configures an ubuntu machine to build docker images. Includes packer to coordinate, docker as the builder, and chef as the provisioner.'
version '0.1.0'

depends 'docker', '~> 0.35.2'
depends 'packer', '~> 0.3.0'
